name: Integration Tests (defra/cdp-portal-tests)
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Publish"]
    types:
      - completed
jobs:
  test:
    uses: defra/cdp-portal-tests/.github/workflows/run-tests.yaml@main
