name: Integration Tests

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Publish"]
    types:
      - completed
jobs:
  test:
    uses: defra/cdp-portal-journey-tests/.github/workflows/journey-tests.yml@main
